I0516 23:51:24.521429 140450165581632 run.py:28] Device: cuda
W0516 23:51:24.971084 140450165581632 utils.py:474] Not applying transforms to coordinates in unrecognized space 'ale_2mm'
I0516 23:51:25.055167 140450165581632 diagnostics.py:438] 7/214 coordinates fall outside of the mask. Removing them.
W0516 23:51:25.408674 140450165581632 utils.py:474] Not applying transforms to coordinates in unrecognized space 'ale_2mm'
I0516 23:51:26.065074 140450165581632 diagnostics.py:438] 91/2125 coordinates fall outside of the mask. Removing them.
W0516 23:51:26.446236 140450165581632 utils.py:474] Not applying transforms to coordinates in unrecognized space 'ale_2mm'
I0516 23:51:26.686643 140450165581632 diagnostics.py:438] 8/668 coordinates fall outside of the mask. Removing them.
W0516 23:51:27.059463 140450165581632 utils.py:474] Not applying transforms to coordinates in unrecognized space 'ale_2mm'
I0516 23:51:27.697146 140450165581632 diagnostics.py:438] 65/2098 coordinates fall outside of the mask. Removing them.
/well/nichols/users/pra123/anaconda3/envs/torch/lib/python3.11/site-packages/patsy/util.py:672: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return _pandas_is_categorical_dtype(dt)
/well/nichols/users/pra123/anaconda3/envs/torch/lib/python3.11/site-packages/patsy/util.py:672: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  return _pandas_is_categorical_dtype(dt)
slurmstepd: error: *** JOB 58584112 ON compg036 CANCELLED AT 2024-05-17T03:50:26 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 58584112.0 ON compg036 CANCELLED AT 2024-05-17T03:50:26 DUE TO TIME LIMIT ***
